# Generated by Django 5.2.17 on 2026-10-05 19:13

import core.clock
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("entries", "0005_stewardgrant"),
        ("intake", "0002_importbatch_importrow_dedupecandidate"),
    ]

    operations = [
        migrations.CreateModel(
            name="AgentJob",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("second_check", "Second Check"),
                            ("recheck", "Recheck"),
                        ],
                        max_length=14,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "Queued"),
                            ("running", "Running"),
                            ("done", "Done"),
                            ("failed", "Failed"),
                            ("stopped", "Stopped"),
                        ],
                        default="queued",
                        max_length=10,
                    ),
                ),
                ("budget_cap_minor", models.PositiveIntegerField()),
                ("spent_minor", models.PositiveIntegerField(default=0)),
                ("tokens_in", models.PositiveIntegerField(default=0)),
                ("tokens_out", models.PositiveIntegerField(default=0)),
                ("model", models.CharField(blank=True, max_length=60)),
                ("stop_reason", models.CharField(blank=True, max_length=120)),
                ("started_at", models.DateTimeField(default=core.clock.now)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="agent_jobs",
                        to="intake.source",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DraftEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("raw", models.JSONField(default=dict)),
                ("evidence_quotes", models.JSONField(default=dict)),
                ("source_urls", models.JSONField(default=list)),
                ("confidence", models.FloatField(default=0.0)),
                ("cost_minor", models.PositiveIntegerField(default=0)),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("staged", "Staged"),
                            ("promoted", "Promoted"),
                            ("rejected", "Rejected"),
                        ],
                        default="staged",
                        max_length=10,
                    ),
                ),
                ("reason", models.CharField(blank=True, max_length=160)),
                ("created_at", models.DateTimeField(default=core.clock.now)),
                (
                    "entry",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="entries.entry",
                    ),
                ),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="drafts",
                        to="agents.agentjob",
                    ),
                ),
            ],
        ),
    ]
