"""Every route and who may use it (rule: an authorisation test covers every route). A new route without an entry here
fails `test_every_route_declares_its_access`."""

PUBLIC, LOGIN, STAFF, WEBHOOK = "public", "login", "staff", "webhook"

ROUTES = {
    "admin/login/": PUBLIC,
    "admin/": STAFF,
    "account/signup/": PUBLIC,
    "account/login/": PUBLIC,
    "account/logout/": PUBLIC,
    "account/verify/<str:token>/": PUBLIC,
    "account/mfa/setup/": PUBLIC,
    "account/mfa/verify/": PUBLIC,
    "account/delete/": LOGIN,
    "account/password/reset/": PUBLIC,
    "account/password/reset/sent/": PUBLIC,
    "account/password/reset/<uidb64>/<token>/": PUBLIC,
    "account/": LOGIN,
    "": PUBLIC,
    "healthz": PUBLIC,
    "robots.txt": PUBLIC,
    "sitemap.xml": PUBLIC,
    "sitemaps/<str:cc>-<int:n>.xml": PUBLIC,
    "prefs/": PUBLIC,
    "prefs/location/": PUBLIC,
    "add/": LOGIN,
    "add/area/": LOGIN,
    "claim/<str:uid>/": LOGIN,
    "wrong/<str:uid>/": PUBLIC,
    "message/<str:uid>/": LOGIN,
    "enquiry/": LOGIN,
    "optout/<str:token>/": PUBLIC,
    "account/enquiries/": LOGIN,
    "account/steward/": LOGIN,
    "account/owner/<str:uid>/": LOGIN,
    "staff/": STAFF,
    "staff/imports/": STAFF,
    "staff/sources/": STAFF,
    "staff/tasks/": STAFF,
    "staff/audit/": STAFF,
    "staff/switches/": STAFF,
    "staff/outbox/": STAFF,
    "staff/<str:key>/": STAFF,
    "staff/<str:key>/<int:pk>/<str:action>/": STAFF,
    "account/tasks/": LOGIN,
    "account/subscription/": LOGIN,
    "account/orders/<str:ref>/": LOGIN,
    "webhooks/payments/<str:provider>/": "webhook",
    "staff/orders/": STAFF,
    "account/tasks/<int:pk>/": LOGIN,
    "account/contributor/": LOGIN,
    "_f/near-you/": PUBLIC,
    "_f/list/": PUBLIC,
    "_f/entry/<str:uid>/": PUBLIC,
    "e/<str:uid>/": PUBLIC,
    "e/<str:uid>/<slug:slug>/": PUBLIC,
    "search/": PUBLIC,
    "about/": PUBLIC,
    "terms/": PUBLIC,
    "privacy/": PUBLIC,
    "plans/": PUBLIC,
    "sources/": PUBLIC,
    "how-checks-work/": PUBLIC,
    "contributors/rules/": PUBLIC,
    "^(?P<path>[\\w\\-]+(?:/[\\w\\-]+)*)/$": PUBLIC,
}
