from django.urls import path, re_path

from . import forms_views, staff_views, static_views, task_views, views

urlpatterns = [
    path("", views.world, name="world"),
    path("robots.txt", views.robots_txt),
    path("healthz", views.healthz),
    path("sitemap.xml", views.sitemap_index),
    path("sitemaps/<str:cc>-<int:n>.xml", views.sitemap_shard),
    path("prefs/", views.prefs, name="prefs"),
    path("search/", views.search_page),
    path("prefs/location/", views.prefs_location),
    path("about/", static_views.page, {"key": "about"}),
    path("terms/", static_views.page, {"key": "terms"}),
    path("privacy/", static_views.page, {"key": "privacy"}),
    path("plans/", static_views.page, {"key": "plans"}),
    path("sources/", static_views.page, {"key": "sources"}),
    path("how-checks-work/", static_views.page, {"key": "how-checks-work"}),
    path("how-lists-are-ordered/", static_views.page, {"key": "how-lists-are-ordered"}),
    path("go/ad/<int:pk>/", views.ad_click),
    path("account/ads/", forms_views.ads_page),
    path("account/payout/", forms_views.payout_page),
    path("account/my-data/", forms_views.my_data),
    path("contributors/rules/", static_views.page, {"key": "contributors/rules"}),
    path("add/", forms_views.add_entry),
    path("add/area/", forms_views.add_area),
    path("claim/<str:uid>/", forms_views.claim),
    path("wrong/<str:uid>/", forms_views.wrong),
    path("message/<str:uid>/", forms_views.message),
    path("enquiry/", forms_views.enquiry_many),
    path("optout/<str:token>/", forms_views.optout),
    path("account/enquiries/", forms_views.my_enquiries),
    path("account/steward/", forms_views.steward_page),
    path("account/campaigns/", forms_views.campaigns_page),
    path("account/owner/<str:uid>/", forms_views.owner_page),
    path("staff/", staff_views.index),
    path("staff/imports/", staff_views.imports),
    path("staff/sources/", staff_views.sources),
    path("staff/tasks/", staff_views.tasks),
    path("staff/audit/", staff_views.audit_view),
    path("staff/switches/", staff_views.switches),
    path("staff/outbox/", staff_views.outbox),
    path("staff/agents/", staff_views.agents_page),
    path("staff/jobs/", staff_views.jobs_page),
    path("staff/statistics/", staff_views.statistics),
    path("staff/ledger/", staff_views.ledger_page),
    path("staff/metrics/", staff_views.metrics_page),
    path("staff/subject-access/", staff_views.subject_access),
    path("staff/extracts/", staff_views.extracts),
    path("staff/extracts/<int:pk>/download/", staff_views.extract_download),
    path("staff/<str:key>/", staff_views.show_queue),
    path("staff/<str:key>/<int:pk>/<str:action>/", staff_views.act),
    path("account/tasks/", task_views.my_tasks),
    path("account/tasks/<int:pk>/", task_views.task_detail),
    path("account/contributor/", task_views.contributor_page),
    path("account/contributor/onboarding/", task_views.onboarding_page),
    path("account/certificates/<int:pk>/", task_views.certificate_page),
    path("certificate/<str:code>/", task_views.certificate_verify),
    path("_f/ref/", views.frag_ref),
    path("_f/near-you/", views.frag_near_you),
    path("_f/list/", views.frag_list),
    path("_f/entry/<str:uid>/", views.frag_entry),
    path("e/<str:uid>/", views.entry_page),
    path("e/<str:uid>/<slug:slug>/", views.entry_page),
    re_path(r"^(?P<path>[\w\-]+(?:/[\w\-]+)*)/$", views.dispatch, name="dispatch"),
]
