# Generated by Django 5.2.17 on 2026-10-05 18:45

import core.clock
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("entries", "0003_mergemap"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Report",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("closed", "Closed"),
                            ("wrong", "Wrong"),
                            ("duplicate", "Duplicate"),
                            ("fake", "Fake"),
                            ("remove_my_data", "Remove My Data"),
                            ("suggest_edit", "Suggest Edit"),
                            ("claim_dispute", "Claim Dispute"),
                        ],
                        max_length=20,
                    ),
                ),
                ("text", models.TextField(blank=True, max_length=2000)),
                ("reporter_hash", models.CharField(blank=True, max_length=64)),
                ("reporter_contact_enc", models.TextField(blank=True)),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("assigned", "Assigned"),
                            ("upheld", "Upheld"),
                            ("rejected", "Rejected"),
                        ],
                        default="open",
                        max_length=10,
                    ),
                ),
                ("resolution", models.CharField(blank=True, max_length=300)),
                ("created_at", models.DateTimeField(default=core.clock.now)),
                ("decided_at", models.DateTimeField(blank=True, null=True)),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "entry",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reports",
                        to="entries.entry",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SuggestedEdit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("field_key", models.CharField(max_length=60)),
                ("new_value", models.JSONField()),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("accepted", "Accepted"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(default=core.clock.now)),
                ("decided_by_id", models.BigIntegerField(blank=True, null=True)),
                (
                    "actor",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "entry",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="suggested_edits",
                        to="entries.entry",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Takedown",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("requester_hash", models.CharField(blank=True, max_length=64)),
                ("kind", models.CharField(max_length=20)),
                ("legal_basis", models.CharField(blank=True, max_length=120)),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("done", "Done"),
                            ("refused", "Refused"),
                        ],
                        default="open",
                        max_length=10,
                    ),
                ),
                ("due_at", models.DateTimeField(blank=True, null=True)),
                ("log", models.JSONField(blank=True, default=list)),
                ("created_at", models.DateTimeField(default=core.clock.now)),
                ("done_at", models.DateTimeField(blank=True, null=True)),
                (
                    "entry",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="takedowns",
                        to="entries.entry",
                    ),
                ),
            ],
        ),
    ]
