# Generated by Django 5.2.17 on 2026-10-05 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Source",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=160, unique=True)),
                (
                    "tier",
                    models.CharField(
                        choices=[
                            ("green", "Green"),
                            ("amber", "Amber"),
                            ("red", "Red"),
                        ],
                        default="amber",
                        max_length=6,
                    ),
                ),
                ("licence_text", models.TextField(blank=True)),
                ("terms_url", models.URLField(blank=True)),
                ("robots_decision", models.CharField(blank=True, max_length=60)),
                ("allowed_uses", models.JSONField(blank=True, default=list)),
                ("bulk_permission", models.BooleanField(default=False)),
                ("personal_data_rules", models.TextField(blank=True)),
                ("attribution_text", models.CharField(blank=True, max_length=300)),
                ("reviewed_by", models.CharField(blank=True, max_length=120)),
                ("reviewed_on", models.DateField(blank=True, null=True)),
                ("status", models.CharField(default="active", max_length=10)),
            ],
        ),
    ]
