# Generated by Django 5.2.17 on 2026-10-05 16:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("entries", "0003_mergemap"),
        ("intake", "0001_initial"),
        ("places", "0002_indexes"),
        ("taxonomy", "0002_indexes"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ImportBatch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("declared_rights", models.BooleanField(default=False)),
                ("raw_text", models.TextField()),
                ("mapping", models.JSONField(blank=True, default=dict)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("uploaded", "Uploaded"),
                            ("mapped", "Mapped"),
                            ("done", "Done"),
                            ("failed", "Failed"),
                        ],
                        default="uploaded",
                        max_length=10,
                    ),
                ),
                ("counts", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                (
                    "concept",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="taxonomy.concept",
                    ),
                ),
                (
                    "place",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="places.place",
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="batches",
                        to="intake.source",
                    ),
                ),
                (
                    "uploader",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ImportRow",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("line_no", models.PositiveIntegerField()),
                ("raw", models.JSONField(default=dict)),
                ("normalised", models.JSONField(blank=True, default=dict)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "New"),
                            ("duplicate", "Duplicate"),
                            ("held", "Held"),
                            ("error", "Error"),
                            ("drafted", "Drafted"),
                        ],
                        default="new",
                        max_length=10,
                    ),
                ),
                ("message", models.CharField(blank=True, max_length=200)),
                (
                    "batch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rows",
                        to="intake.importbatch",
                    ),
                ),
                (
                    "entry",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="entries.entry",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DedupeCandidate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("score", models.FloatField()),
                ("features", models.JSONField(default=dict)),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("auto_merged", "Auto Merged"),
                            ("rejected", "Rejected"),
                            ("merged", "Merged"),
                        ],
                        default="pending",
                        max_length=12,
                    ),
                ),
                ("decided_by_id", models.BigIntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "a_entry",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="entries.entry",
                    ),
                ),
                (
                    "b_entry",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="entries.entry",
                    ),
                ),
            ],
            options={
                "constraints": [models.UniqueConstraint(fields=("a_entry", "b_entry"), name="uniq_dedupe_pair")],
            },
        ),
    ]
