# Generated by Django 5.2.17 on 2026-10-05 19:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("entries", "0005_stewardgrant"),
        ("intake", "0002_importbatch_importrow_dedupecandidate"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExternalRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("external_id", models.CharField(max_length=80)),
                ("outcome", models.CharField(max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "entry",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="entries.entry",
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="records",
                        to="intake.source",
                    ),
                ),
            ],
            options={
                "constraints": [models.UniqueConstraint(fields=("source", "external_id"), name="uniq_external_record")],
            },
        ),
    ]
