# Generated by Django 5.2.17 on 2026-10-06 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("intake", "0003_externalrecord"),
    ]

    operations = [
        migrations.AddField(
            model_name="importbatch",
            name="accuracy",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="importbatch",
            name="audit_sample",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="importbatch",
            name="published_through",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="importbatch",
            name="quality",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="importbatch",
            name="staged_through",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="importrow",
            name="quality",
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name="importbatch",
            name="status",
            field=models.CharField(
                choices=[
                    ("uploaded", "Uploaded"),
                    ("mapped", "Mapped"),
                    ("done", "Done"),
                    ("failed", "Failed"),
                    ("staged", "Staged"),
                    ("audited", "Audited"),
                    ("rejected", "Rejected"),
                    ("rolled_back", "Rolled Back"),
                ],
                default="uploaded",
                max_length=12,
            ),
        ),
        migrations.AlterField(
            model_name="importrow",
            name="status",
            field=models.CharField(
                choices=[
                    ("new", "New"),
                    ("duplicate", "Duplicate"),
                    ("held", "Held"),
                    ("error", "Error"),
                    ("drafted", "Drafted"),
                    ("staged", "Staged"),
                ],
                default="new",
                max_length=10,
            ),
        ),
    ]
