# Generated by Django 5.2.17 on 2026-10-05 19:00

import core.clock
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("entries", "0004_companysection"),
        ("taxonomy", "0002_indexes"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.SlugField(unique=True)),
                ("name", models.CharField(max_length=100)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("subscription", "Subscription"),
                            ("list_access", "List Access"),
                            ("listing", "Listing"),
                            ("rank", "Rank"),
                            ("extract", "Extract"),
                        ],
                        max_length=14,
                    ),
                ),
                ("price_minor", models.BigIntegerField()),
                ("currency", models.CharField(default="USD", max_length=3)),
                ("period_days", models.PositiveIntegerField(default=30)),
                ("active", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("paid", "Paid"),
                            ("fulfilled", "Fulfilled"),
                            ("refunded", "Refunded"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=10,
                    ),
                ),
                ("currency", models.CharField(max_length=3)),
                ("amount_minor", models.BigIntegerField()),
                ("tax_minor", models.BigIntegerField(default=0)),
                ("scope_path", models.CharField(blank=True, max_length=500)),
                ("created_at", models.DateTimeField(default=core.clock.now)),
                ("ref", models.CharField(max_length=40, unique=True)),
                (
                    "buyer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="orders",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "concept",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="taxonomy.concept",
                    ),
                ),
                (
                    "entry",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="entries.entry",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="billing.product",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Invoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.CharField(max_length=20, unique=True)),
                ("issued_at", models.DateTimeField(default=core.clock.now)),
                ("lines", models.JSONField(default=list)),
                (
                    "order",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="invoice",
                        to="billing.order",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("provider", models.CharField(max_length=20)),
                ("provider_ref", models.CharField(max_length=80)),
                ("amount_minor", models.BigIntegerField()),
                ("fees_minor", models.BigIntegerField(default=0)),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("succeeded", "Succeeded"),
                            ("failed", "Failed"),
                            ("refunded", "Refunded"),
                        ],
                        max_length=10,
                    ),
                ),
                ("recorded_by_id", models.BigIntegerField(blank=True, null=True)),
                ("raw", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(default=core.clock.now)),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payments",
                        to="billing.order",
                    ),
                ),
            ],
            options={
                "constraints": [models.UniqueConstraint(fields=("provider", "provider_ref"), name="uniq_payment_ref")],
            },
        ),
    ]
