# Generated by Django 5.2.17 on 2026-10-05 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="campaign_id",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="kind",
            field=models.CharField(
                choices=[
                    ("subscription", "Subscription"),
                    ("list_access", "List Access"),
                    ("listing", "Listing"),
                    ("rank", "Rank"),
                    ("extract", "Extract"),
                    ("outreach", "Outreach"),
                ],
                max_length=14,
            ),
        ),
    ]
