# Generated by Django 5.2.17 on 2026-10-05 19:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0003_order_ad_id_alter_product_kind"),
    ]

    operations = [
        migrations.CreateModel(
            name="InvoiceCounter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.PositiveSmallIntegerField(unique=True)),
                ("last", models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name="invoice",
            name="buyer",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="invoice",
            name="credit_for",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="credits",
                to="billing.invoice",
            ),
        ),
        migrations.AddField(
            model_name="invoice",
            name="currency",
            field=models.CharField(default="USD", max_length=3),
        ),
        migrations.AddField(
            model_name="invoice",
            name="kind",
            field=models.CharField(
                choices=[("invoice", "Invoice"), ("credit_note", "Credit Note")],
                default="invoice",
                max_length=12,
            ),
        ),
        migrations.AddField(
            model_name="invoice",
            name="seller",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="invoice",
            name="tax_rate",
            field=models.CharField(default="0", max_length=10),
        ),
        migrations.AddField(
            model_name="order",
            name="billing",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="order",
            name="tax_rate",
            field=models.CharField(default="0", max_length=10),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="invoices",
                to="billing.order",
            ),
        ),
        migrations.AddConstraint(
            model_name="invoice",
            constraint=models.UniqueConstraint(
                condition=models.Q(("kind", "invoice")),
                fields=("order",),
                name="one_invoice_per_order",
            ),
        ),
    ]
