# Generated by Django 5.2.17 on 2026-10-05 19:15

import core.clock
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("entries", "0005_stewardgrant"),
        ("outreach", "0001_initial"),
        ("taxonomy", "0002_indexes"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Campaign",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("scope_path", models.CharField(max_length=500)),
                ("variables", models.JSONField(blank=True, default=dict)),
                ("channel", models.CharField(max_length=10)),
                ("country_code", models.CharField(max_length=2)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("sending", "Sending"),
                            ("done", "Done"),
                            ("paused", "Paused"),
                        ],
                        default="draft",
                        max_length=10,
                    ),
                ),
                ("budget_minor", models.PositiveIntegerField(default=0)),
                ("spent_minor", models.PositiveIntegerField(default=0)),
                ("funded", models.BooleanField(default=False)),
                ("approved_by_id", models.BigIntegerField(blank=True, null=True)),
                ("pause_reason", models.CharField(blank=True, max_length=120)),
                ("created_at", models.DateTimeField(default=core.clock.now)),
                (
                    "buyer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="campaigns",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "concept",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="taxonomy.concept",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("channel", models.CharField(max_length=10)),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("queued", "Queued"),
                            ("sent", "Sent"),
                            ("delivered", "Delivered"),
                            ("read", "Read"),
                            ("replied", "Replied"),
                            ("failed", "Failed"),
                            ("opted_out", "Opted Out"),
                        ],
                        default="queued",
                        max_length=10,
                    ),
                ),
                (
                    "provider_id",
                    models.CharField(blank=True, db_index=True, max_length=80),
                ),
                ("reply_text", models.TextField(blank=True)),
                ("cost_minor", models.PositiveIntegerField(default=0)),
                ("ts", models.DateTimeField(default=core.clock.now)),
                (
                    "campaign",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="outreach.campaign",
                    ),
                ),
                (
                    "contact",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="entries.contact",
                    ),
                ),
                (
                    "entry",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="entries.entry",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DeliveryEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("event", models.CharField(max_length=12)),
                ("payload", models.JSONField(blank=True, default=dict)),
                ("ts", models.DateTimeField(default=core.clock.now)),
                (
                    "message",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="outreach.message",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MessageTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.SlugField()),
                ("channel", models.CharField(max_length=10)),
                ("language", models.CharField(default="en", max_length=5)),
                ("body", models.TextField()),
                ("provider_state", models.CharField(default="draft", max_length=10)),
                ("approved_by_id", models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("key", "channel", "language"),
                        name="uniq_message_template",
                    )
                ],
            },
        ),
        migrations.AddField(
            model_name="campaign",
            name="template",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="outreach.messagetemplate",
            ),
        ),
        migrations.CreateModel(
            name="SupplierVerification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("company", models.CharField(max_length=120)),
                ("state", models.CharField(default="pending", max_length=10)),
                ("decided_by_id", models.BigIntegerField(blank=True, null=True)),
                ("decided_at", models.DateTimeField(blank=True, null=True)),
                ("note", models.CharField(blank=True, max_length=200)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="supplier",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
