# Generated by Django 5.2.17 on 2026-10-05 18:45

import core.clock
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("entries", "0003_mergemap"),
        ("places", "0002_indexes"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ContributorProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("level", models.PositiveSmallIntegerField(default=0)),
                ("points", models.PositiveIntegerField(default=0)),
                ("ref_code", models.CharField(max_length=12, unique=True)),
                ("accuracy", models.FloatField(blank=True, null=True)),
                ("suspended", models.BooleanField(default=False)),
                ("onboarded_at", models.DateTimeField(blank=True, null=True)),
                ("declared_rights_at", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contributor",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Reward",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("kind", models.CharField(max_length=20)),
                ("detail", models.CharField(blank=True, max_length=120)),
                ("granted_at", models.DateTimeField(default=core.clock.now)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rewards",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("verify", "Verify"),
                            ("survey", "Survey"),
                            ("dedupe_review", "Dedupe Review"),
                            ("area_review", "Area Review"),
                            ("translate", "Translate"),
                        ],
                        max_length=14,
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("assigned", "Assigned"),
                            ("done", "Done"),
                            ("skipped", "Skipped"),
                        ],
                        default="open",
                        max_length=10,
                    ),
                ),
                ("field_group", models.CharField(default="identity", max_length=20)),
                ("due_at", models.DateTimeField(blank=True, null=True)),
                ("result", models.JSONField(blank=True, default=dict)),
                ("minutes", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("canary", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(default=core.clock.now)),
                ("done_at", models.DateTimeField(blank=True, null=True)),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tasks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "entry",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tasks",
                        to="entries.entry",
                    ),
                ),
                (
                    "place",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="places.place",
                    ),
                ),
            ],
        ),
    ]
