# Generated by Django 5.2.17 on 2026-10-05 19:14

import core.clock
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("entries", "0005_stewardgrant"),
        ("intake", "0002_importbatch_importrow_dedupecandidate"),
        ("volunteers", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditSample",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("original_verifier_id", models.BigIntegerField(blank=True, null=True)),
                ("correct", models.BooleanField(null=True)),
                ("created_at", models.DateTimeField(default=core.clock.now)),
                (
                    "entry",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="audit_samples",
                        to="entries.entry",
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="intake.source",
                    ),
                ),
                (
                    "task",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="audit_sample",
                        to="volunteers.task",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CanaryEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("purpose", models.CharField(max_length=10)),
                ("planted_at", models.DateTimeField(default=core.clock.now)),
                ("note", models.CharField(blank=True, max_length=120)),
                (
                    "entry",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="canary",
                        to="entries.entry",
                    ),
                ),
            ],
        ),
    ]
