# Generated by Django 5.2.17 on 2026-10-05 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("volunteers", "0002_auditsample_canaryentry"),
    ]

    operations = [
        migrations.AddField(
            model_name="contributorprofile",
            name="quiz_score",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="contributorprofile",
            name="show_credit",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="reward",
            name="code",
            field=models.CharField(blank=True, db_index=True, max_length=24),
        ),
    ]
