# Generated by Django 5.2.17 on 2026-10-05 16:35

import core.clock
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("taxonomy", "0002_indexes"),
    ]

    operations = [
        migrations.CreateModel(
            name="RollupCell",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("country_code", models.CharField(max_length=2)),
                ("place_path", models.CharField(max_length=500)),
                ("total", models.PositiveIntegerField(default=0)),
                ("published", models.PositiveIntegerField(default=0)),
                ("by_level", models.JSONField(default=dict)),
                ("verified_12m", models.PositiveIntegerField(default=0)),
                ("with_contact_pct", models.PositiveSmallIntegerField(default=0)),
                ("updated_at", models.DateTimeField(default=core.clock.now)),
                (
                    "concept",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="taxonomy.concept",
                    ),
                ),
            ],
            options={
                "indexes": [models.Index(fields=["country_code", "place_path"], name="rollup_place_idx")],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("country_code", "place_path", "concept"),
                        name="uniq_rollup_cell",
                    )
                ],
            },
        ),
    ]
