# Generated by Django 5.2.17 on 2026-10-05 18:56

import core.clock
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analytics", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(db_index=True, max_length=40)),
                ("ts", models.DateTimeField(db_index=True, default=core.clock.now)),
                ("subject_hash", models.CharField(blank=True, max_length=64)),
                ("props", models.JSONField(blank=True, default=dict)),
            ],
        ),
    ]
