# Generated by Django 5.2.17 on 2026-10-05 19:27

import core.clock
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analytics", "0002_event"),
        ("taxonomy", "0002_indexes"),
    ]

    operations = [
        migrations.CreateModel(
            name="Extract",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_by_id", models.BigIntegerField()),
                ("scope_path", models.CharField(blank=True, max_length=500)),
                ("order_ref", models.CharField(blank=True, max_length=40)),
                ("purpose", models.CharField(blank=True, max_length=200)),
                ("buyer_label", models.CharField(blank=True, max_length=120)),
                ("row_count", models.PositiveIntegerField(default=0)),
                ("trace_count", models.PositiveIntegerField(default=0)),
                ("sha256", models.CharField(blank=True, max_length=64)),
                ("file_name", models.CharField(blank=True, max_length=120)),
                ("created_at", models.DateTimeField(default=core.clock.now)),
                (
                    "concept",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="taxonomy.concept",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TraceEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(db_index=True, max_length=200)),
                ("website", models.CharField(db_index=True, max_length=200)),
                ("address_text", models.CharField(max_length=400)),
                (
                    "extract",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="traces",
                        to="analytics.extract",
                    ),
                ),
            ],
        ),
    ]
