# Generated by Django 5.2.17 on 2026-10-05 16:29

import core.clock
import core.ulid
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Place",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uid",
                    models.CharField(
                        default=core.ulid.new_ulid,
                        editable=False,
                        max_length=26,
                        unique=True,
                    ),
                ),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("world", "World"),
                            ("region", "Region"),
                            ("country", "Country"),
                            ("admin1", "Admin1"),
                            ("admin2", "Admin2"),
                            ("admin3", "Admin3"),
                            ("city", "City"),
                            ("area", "Area"),
                            ("society", "Society"),
                            ("street", "Street"),
                        ],
                        max_length=10,
                    ),
                ),
                ("local_level_label", models.CharField(blank=True, max_length=40)),
                ("iso_code", models.CharField(blank=True, max_length=10)),
                (
                    "country_code",
                    models.CharField(blank=True, db_index=True, max_length=2),
                ),
                ("slug", models.SlugField(max_length=120)),
                ("path", models.CharField(db_index=True, max_length=500)),
                ("depth", models.PositiveSmallIntegerField(default=0)),
                (
                    "centre_lat",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "centre_lon",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                ("population_band", models.CharField(blank=True, max_length=20)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("proposed", "Proposed"),
                            ("rejected", "Rejected"),
                            ("merged", "Merged"),
                        ],
                        default="active",
                        max_length=10,
                    ),
                ),
                ("source_id", models.BigIntegerField(blank=True, null=True)),
                ("geonames_id", models.BigIntegerField(blank=True, null=True)),
                ("wikidata_id", models.CharField(blank=True, max_length=20)),
                ("created_at", models.DateTimeField(default=core.clock.now)),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="children",
                        to="places.place",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PlaceName",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("language", models.CharField(max_length=10)),
                ("script", models.CharField(blank=True, max_length=10)),
                ("name", models.CharField(max_length=200)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("preferred", "Preferred"),
                            ("alias", "Alias"),
                            ("transliteration", "Transliteration"),
                        ],
                        default="preferred",
                        max_length=20,
                    ),
                ),
                ("name_fold", models.CharField(db_index=True, max_length=200)),
                (
                    "place",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="names",
                        to="places.place",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PlaceProposal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("proposed_name", models.CharField(max_length=200)),
                ("language", models.CharField(default="en", max_length=10)),
                ("proposer_id", models.BigIntegerField(blank=True, null=True)),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("duplicate", "Duplicate"),
                        ],
                        default="pending",
                        max_length=10,
                    ),
                ),
                ("decided_by", models.BigIntegerField(blank=True, null=True)),
                ("reason", models.CharField(blank=True, max_length=200)),
                ("created_at", models.DateTimeField(default=core.clock.now)),
                (
                    "duplicate_of",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="places.place",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="proposals",
                        to="places.place",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="place",
            index=models.Index(
                fields=["path"],
                name="place_path_prefix",
                opclasses=["varchar_pattern_ops"],
            ),
        ),
        migrations.AddConstraint(
            model_name="place",
            constraint=models.UniqueConstraint(
                fields=("parent", "slug"), name="places_uniq_slug_per_parent"
            ),
        ),
        migrations.AddConstraint(
            model_name="place",
            constraint=models.UniqueConstraint(
                condition=models.Q(("parent__isnull", True)),
                fields=("slug",),
                name="uniq_root_slug",
            ),
        ),
    ]
