# Generated by Django 5.2.17 on 2026-10-05 19:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("places", "0002_indexes"),
    ]

    operations = [
        migrations.CreateModel(
            name="PlaceExternalId",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("scheme", models.CharField(max_length=20)),
                ("value", models.CharField(max_length=80)),
                (
                    "place",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="external_ids",
                        to="places.place",
                    ),
                ),
            ],
            options={
                "constraints": [models.UniqueConstraint(fields=("scheme", "value"), name="uniq_place_external_id")],
            },
        ),
    ]
