# Generated by Django 5.2.17 on 2026-10-05 16:29

import core.clock
import core.ulid
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AddonTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.SlugField(unique=True)),
                ("version", models.PositiveIntegerField(default=1)),
                ("status", models.CharField(default="active", max_length=10)),
                ("description", models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="Concept",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uid",
                    models.CharField(
                        default=core.ulid.new_ulid,
                        editable=False,
                        max_length=26,
                        unique=True,
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("family", "Family"),
                            ("list_type", "List Type"),
                            ("speciality", "Speciality"),
                            ("service", "Service"),
                            ("product", "Product"),
                        ],
                        max_length=12,
                    ),
                ),
                ("slug", models.SlugField(max_length=120)),
                (
                    "entity_type_default",
                    models.CharField(default="business", max_length=12),
                ),
                (
                    "natural_scale",
                    models.CharField(
                        choices=[
                            ("hyper_local", "Hyper Local"),
                            ("city", "City"),
                            ("national", "National"),
                            ("global", "Global"),
                        ],
                        default="city",
                        max_length=12,
                    ),
                ),
                ("status", models.CharField(default="active", max_length=10)),
                ("created_by_id", models.BigIntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(default=core.clock.now)),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="children",
                        to="taxonomy.concept",
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="concepts",
                        to="taxonomy.addontemplate",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ConceptCrosswalk",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("system", models.CharField(max_length=20)),
                ("code", models.CharField(max_length=80)),
                ("match_type", models.CharField(default="exact", max_length=10)),
                (
                    "concept",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="crosswalks",
                        to="taxonomy.concept",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ConceptLabel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("language", models.CharField(max_length=10)),
                ("region", models.CharField(blank=True, max_length=2)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("preferred", "Preferred"),
                            ("synonym", "Synonym"),
                            ("local", "Local"),
                            ("misspelling", "Misspelling"),
                        ],
                        default="preferred",
                        max_length=12,
                    ),
                ),
                ("text", models.CharField(max_length=200)),
                ("text_fold", models.CharField(db_index=True, max_length=200)),
                (
                    "concept",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="labels",
                        to="taxonomy.concept",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ListTypeSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("index_threshold", models.PositiveIntegerField(default=10)),
                ("row_descriptor_field", models.CharField(blank=True, max_length=60)),
                ("actions_allowed", models.JSONField(blank=True, default=list)),
                ("share_hidden", models.BooleanField(default=False)),
                ("is_individual", models.BooleanField(default=False)),
                ("is_child_facing", models.BooleanField(default=False)),
                ("is_health", models.BooleanField(default=False)),
                ("price_required_date", models.BooleanField(default=True)),
                (
                    "concept",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="settings",
                        to="taxonomy.concept",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ReservedSlug",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.SlugField(max_length=120)),
                ("kind", models.CharField(max_length=10)),
            ],
            options={
                "constraints": [models.UniqueConstraint(fields=("slug", "kind"), name="uniq_reserved_slug_kind")],
            },
        ),
        migrations.CreateModel(
            name="AddonField",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.SlugField(max_length=60)),
                ("label_key", models.CharField(max_length=120)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("text", "Text"),
                            ("number", "Number"),
                            ("enum", "Enum"),
                            ("bool", "Bool"),
                            ("date", "Date"),
                            ("concept_list", "Concept List"),
                            ("money", "Money"),
                            ("identifier_list", "Identifier List"),
                            ("place_list", "Place List"),
                        ],
                        max_length=20,
                    ),
                ),
                ("validation", models.JSONField(blank=True, default=dict)),
                ("required_for_publish", models.BooleanField(default=False)),
                (
                    "show",
                    models.CharField(
                        choices=[
                            ("P", "Public"),
                            ("L", "Locked"),
                            ("H", "Hidden"),
                            ("I", "Internal"),
                        ],
                        default="P",
                        max_length=1,
                    ),
                ),
                ("filterable", models.BooleanField(default=False)),
                ("row_descriptor", models.BooleanField(default=False)),
                ("provisional", models.BooleanField(default=False)),
                ("version", models.PositiveIntegerField(default=1)),
                ("deprecated_at", models.DateTimeField(blank=True, null=True)),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fields",
                        to="taxonomy.addontemplate",
                    ),
                ),
            ],
            options={
                "constraints": [models.UniqueConstraint(fields=("template", "key"), name="uniq_addon_field")],
            },
        ),
        migrations.AddConstraint(
            model_name="concept",
            constraint=models.UniqueConstraint(fields=("kind", "slug"), name="uniq_concept_slug_per_kind"),
        ),
    ]
