# Generated by Django 5.2.17 on 2026-10-06 10:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("places", "0003_placeexternalid"),
        ("taxonomy", "0002_indexes"),
    ]

    operations = [
        migrations.CreateModel(
            name="PlaceList",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "concept",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stored_lists",
                        to="taxonomy.concept",
                    ),
                ),
                (
                    "place",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stored_lists",
                        to="places.place",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["concept", "place"], name="placelist_concept_place"
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("place", "concept"), name="uniq_list_per_place_and_type"
                    )
                ],
            },
        ),
    ]
