# Generated by Django 5.2.17 on 2026-10-05 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("access", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="QuotaCounter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("subject", models.CharField(max_length=64)),
                ("key", models.CharField(max_length=30)),
                ("day", models.DateField()),
                ("count", models.PositiveIntegerField(default=0)),
            ],
            options={
                "constraints": [models.UniqueConstraint(fields=("subject", "key", "day"), name="uniq_quota_counter")],
            },
        ),
    ]
