# Generated by Django 5.2.17 on 2026-10-05 19:24

import core.clock
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("access", "0002_quotacounter"),
        ("entries", "0005_stewardgrant"),
        ("taxonomy", "0002_indexes"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Ad",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("scope_path", models.CharField(blank=True, max_length=500)),
                ("headline", models.CharField(max_length=80)),
                ("body", models.CharField(blank=True, max_length=160)),
                ("starts_at", models.DateTimeField(default=core.clock.now)),
                ("ends_at", models.DateTimeField()),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("active", "Active"),
                            ("rejected", "Rejected"),
                            ("ended", "Ended"),
                        ],
                        default="pending",
                        max_length=10,
                    ),
                ),
                ("shown", models.PositiveIntegerField(default=0)),
                ("clicks", models.PositiveIntegerField(default=0)),
                ("order_ref", models.CharField(blank=True, max_length=40)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "advertiser",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ads",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "concept",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="taxonomy.concept",
                    ),
                ),
                (
                    "entry",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ads",
                        to="entries.entry",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Placement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("scope_path", models.CharField(max_length=500)),
                ("level", models.CharField(max_length=10)),
                ("slot", models.PositiveSmallIntegerField()),
                ("price_minor", models.BigIntegerField(default=0)),
                ("currency", models.CharField(default="USD", max_length=3)),
                ("starts_at", models.DateTimeField(default=core.clock.now)),
                ("ends_at", models.DateTimeField()),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("ended", "Ended"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="active",
                        max_length=10,
                    ),
                ),
                ("order_ref", models.CharField(blank=True, max_length=40)),
                ("label", models.CharField(default="Sponsored", max_length=20)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "concept",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="taxonomy.concept",
                    ),
                ),
                (
                    "entry",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="placements",
                        to="entries.entry",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["scope_path", "concept", "state"],
                        name="placement_lookup",
                    )
                ],
            },
        ),
    ]
