EN = {
    "site": "AllLists",
    "tagline": "Lists of anything, checked and dated.",
    "skip": "Skip to results",
    "search": "Search this list",
    "search_go": "Search",
    "search_everything": "Search lists and places",
    "theme": "Theme",
    "language": "Language",
    "home": "World",
    "countries": "Countries",
    "places_in": "Places in {place}",
    "lists_here": "Lists here",
    "list_title": "{list_type} in {place}",
    "scope_line": "{list_type} listed in {place} and the places inside it.",
    "n_entries": {"one": "{n} entry", "other": "{n} entries"},
    "n_published": {"one": "{n} listed", "other": "{n} listed"},
    "awaiting": "{n} awaiting verification",
    "trust_line": "{published} published, {awaiting} awaiting verification. Last checked {date}.",
    "trust_hero_label": "Checked by a person",
    "last_checked": "Last checked {date}",
    "checked_on": "Checked {date} · {age}",
    "age_today": "today",
    "age_days": {"one": "{n} day ago", "other": "{n} days ago"},
    "age_weeks": {"one": "{n} week ago", "other": "{n} weeks ago"},
    "age_months": {"one": "{n} month ago", "other": "{n} months ago"},
    "age_years": {"one": "{n} year ago", "other": "{n} years ago"},
    "check_key_title": "What the checks mean",
    "level_surveyor": "Surveyor-verified",
    "level_owner": "Owner-verified",
    "level_ai": "AI-checked",
    "level_none": "Not verified yet",
    "level_surveyor_help": "An independent AllLists surveyor checked this by call or visit.",
    "level_owner_help": "The owner or manager of the business confirmed this.",
    "level_ai_help": "A computer program compared this with other sources. A person has not checked it.",
    "level_none_help": "Nobody has checked this yet.",
    "legend_surveyor": "Surveyor-verified",
    "legend_owner": "Owner-verified",
    "legend_ai": "AI-checked only",
    "areas": "Areas",
    "all_areas": "All areas",
    "area_count": "{area} ({n})",
    "sort": "Sort",
    "sort_name": "Name",
    "sort_checked": "Recently verified",
    "view_list": "List",
    "view_cards": "Cards",
    "clear_filters": "Clear filters",
    "company_page": "Company page",
    "sponsored": "Sponsored",
    "closed": "Closed",
    "moved": "Moved",
    "temporarily_closed": "Temporarily closed",
    "closed_notice": "This business is closed. Its checks are shown as past records.",
    "subscriber_panel_title": "What subscribers also see",
    "subscriber_panel_body": (
        "Street address, exact map pin, size, website, social pages, export markets, minimum order, "
        "prices with dates and certificate details."
    ),
    "subscribe": "Subscribe",
    "share": "Share",
    "share_more": "More options",
    "copy_link": "Copy link",
    "copied": "Link copied",
    "empty_title": "No entries yet",
    "empty_body": "Nobody has listed {list_type} in {place} yet. You can add the first entry.",
    "empty_nearest": "See {list_type} in {place}",
    "add_entry": "Add an entry",
    "suggest_area": "Suggest an area",
    "claim_business": "Claim your business",
    "something_wrong": "Something wrong?",
    "something_wrong_body": (
        "Report a problem, claim this entry, suggest a correction, or ask us to remove or correct your data. It is free."
    ),
    "message_business": "Message this business",
    "page_next": "Next page",
    "page_prev": "Previous page",
    "page_of": "Page {page} of {pages}",
    "provenance": "Where this comes from",
    "as_of": "Counts as of {date}",
    "legal": "A check is a record, not a guarantee. Listings are not endorsements.",
    "privacy": "Privacy and opt-out",
    "terms": "Terms",
    "near_you": "Near you",
    "near_you_guess": "We think you are in {place}. This is a guess from your connection and is not stored.",
    "near_you_chosen": "Showing lists for {place}.",
    "near_you_none": "We could not tell where you are.",
    "change_place": "Change place",
    "widen": "Widen your search",
    "widen_place": "{place}",
    "widen_world": "World",
    "names_only_note": "Outside your own area this list shows names only. Subscribers see the full list.",
    "key_facts": "Key facts",
    "about": "About",
    "specialities": "Specialities",
    "more_n": "+{n} more",
    "area": "Area",
    "category": "Category",
    "entity_type": "Type",
    "business_type": "Business type",
    "languages": "Languages",
    "year_established": "Established",
    "oem": "OEM work",
    "yes": "Yes",
    "no": "No",
    "services": "Services",
    "certificates": "Certificates",
    "checks_title": "How this was checked",
    "checks_none": "No check is current.",
    "check_expired": "expired",
    "check_by": "by {who}",
    "method": "Method: {method}",
    "address": "Address",
    "map_pin": "Map pin",
    "website": "Website",
    "size": "Size",
    "markets": "Export markets",
    "min_order": "Minimum order",
    "social": "Social pages",
    "locked_line": "Subscribers also see {fields}.",
    "not_found": "Page not found",
    "not_found_body": "That address does not exist. Try the world page.",
    "unchecked_notice": "Not verified yet",
    "ad_label": "Advertisement",
    "demo_plan": "Preview plan",
    "plan_free": "Free",
    "plan_subscriber": "Subscriber",
    "title_entry": "{name} – {list_type} in {place} – AllLists",
    "title_list": "{list_type} in {place} – AllLists",
    "title_place": "{place} – lists – AllLists",
    "title_home": "AllLists – lists of anything, checked and dated",
    "addon_business_type": "Business type",
    "addon_product_categories": "Products",
    "addon_year_established": "Established",
    "addon_years_exporting": "Years exporting",
    "addon_export_markets": "Export markets",
    "addon_certifications": "Certifications",
    "addon_verification_tier": "How it was verified",
    "addon_capacity_band": "Capacity",
    "addon_workforce_band": "Workforce",
    "addon_oem": "OEM work",
    "addon_moq": "Minimum order",
    "addon_tax_ids": "Tax and legal IDs",
    "enum_manufacturer": "Manufacturer",
    "enum_trader": "Trader",
    "enum_wholesaler": "Wholesaler",
    "enum_exporter": "Exporter",
    "quota_notice": "You have used today's free views. Subscribers have no daily limit. Free views reset tomorrow.",
    "search_too_short": "Type at least two letters.",
    "search_no_results": "Nothing found.",
    "search_start_list": "Every list exists everywhere, but this one is empty. You can start it:",
    "search_lists": "Lists",
    "search_places": "Places",
    "search_entries": "Businesses in this area",
    "provided_by": "Provided by the company.",
    "company_updated": "updated {date}",
    "cs_about": "About the company",
    "cs_products": "Products and services",
    "cs_capacity": "Capacity and facilities",
    "cs_terms": "Terms and samples",
    "cs_faq": "Questions buyers ask",
    "company_certs": "Certificates the company lists",
    "checked_by_us": "Checked by AllLists",
    "company_says": "Company says",
    "company_prompt": "Is this your business? Add a company page.",
}
