# Draft Urdu wording. Needs review by a native speaker before launch (decision Q-S14).
UR = {
    "tagline": "ہر چیز کی فہرست، جانچی ہوئی اور تاریخ کے ساتھ۔",
    "skip": "نتائج پر جائیں",
    "search": "اس فہرست میں تلاش کریں",
    "search_go": "تلاش",
    "search_everything": "فہرستیں اور مقامات تلاش کریں",
    "theme": "تھیم",
    "language": "زبان",
    "home": "دنیا",
    "countries": "ممالک",
    "places_in": "{place} کے مقامات",
    "lists_here": "یہاں کی فہرستیں",
    "list_title": "{place} میں {list_type}",
    "scope_line": "{place} اور اس کے اندر کے مقامات میں {list_type} کی فہرست۔",
    "n_entries": {"one": "{n} اندراج", "other": "{n} اندراجات"},
    "n_published": {"one": "{n} درج", "other": "{n} درج"},
    "awaiting": "{n} تصدیق کے منتظر",
    "trust_line": "{published} شائع، {awaiting} تصدیق کے منتظر۔ آخری جانچ {date}۔",
    "trust_hero_label": "کسی انسان سے جانچے گئے",
    "last_checked": "آخری جانچ {date}",
    "checked_on": "جانچ {date} · {age}",
    "age_today": "آج",
    "age_days": {"one": "{n} دن پہلے", "other": "{n} دن پہلے"},
    "age_weeks": {"one": "{n} ہفتہ پہلے", "other": "{n} ہفتے پہلے"},
    "age_months": {"one": "{n} مہینہ پہلے", "other": "{n} مہینے پہلے"},
    "age_years": {"one": "{n} سال پہلے", "other": "{n} سال پہلے"},
    "check_key_title": "جانچ کا مطلب",
    "level_surveyor": "سروے کنندہ سے تصدیق شدہ",
    "level_owner": "مالک سے تصدیق شدہ",
    "level_ai": "اے آئی سے جانچا ہوا",
    "level_none": "ابھی تصدیق نہیں ہوئی",
    "level_surveyor_help": "آل لسٹس کے آزاد سروے کنندہ نے کال یا دورے سے جانچا۔",
    "level_owner_help": "کاروبار کے مالک یا منیجر نے اس کی تصدیق کی۔",
    "level_ai_help": "ایک کمپیوٹر پروگرام نے دوسرے ذرائع سے موازنہ کیا۔ کسی انسان نے نہیں جانچا۔",
    "level_none_help": "ابھی تک کسی نے اسے نہیں جانچا۔",
    "legend_surveyor": "سروے کنندہ سے تصدیق شدہ",
    "legend_owner": "مالک سے تصدیق شدہ",
    "legend_ai": "صرف اے آئی سے جانچا ہوا",
    "areas": "علاقے",
    "all_areas": "تمام علاقے",
    "area_count": "{area} ({n})",
    "sort": "ترتیب",
    "sort_name": "نام",
    "sort_checked": "حال ہی میں تصدیق شدہ",
    "view_list": "فہرست",
    "view_cards": "کارڈز",
    "clear_filters": "فلٹر ہٹائیں",
    "company_page": "کمپنی کا صفحہ",
    "sponsored": "اسپانسر شدہ",
    "closed": "بند",
    "moved": "منتقل",
    "temporarily_closed": "عارضی طور پر بند",
    "subscriber_panel_title": "سبسکرائبرز مزید کیا دیکھتے ہیں",
    "subscribe": "سبسکرائب کریں",
    "share": "شیئر",
    "share_more": "مزید اختیارات",
    "copy_link": "لنک کاپی کریں",
    "copied": "لنک کاپی ہو گیا",
    "empty_title": "ابھی کوئی اندراج نہیں",
    "empty_body": "{place} میں {list_type} ابھی کسی نے درج نہیں کیے۔ آپ پہلا اندراج شامل کر سکتے ہیں۔",
    "add_entry": "اندراج شامل کریں",
    "suggest_area": "علاقہ تجویز کریں",
    "claim_business": "اپنے کاروبار پر دعویٰ کریں",
    "something_wrong": "کچھ غلط ہے؟",
    "message_business": "اس کاروبار کو پیغام بھیجیں",
    "page_next": "اگلا صفحہ",
    "page_prev": "پچھلا صفحہ",
    "page_of": "صفحہ {page} از {pages}",
    "legal": "جانچ ایک ریکارڈ ہے، ضمانت نہیں۔ فہرست میں شامل ہونا تائید نہیں۔",
    "privacy": "رازداری اور اخراج",
    "terms": "شرائط",
    "near_you": "آپ کے قریب",
    "near_you_guess": "ہمارا اندازہ ہے کہ آپ {place} میں ہیں۔ یہ آپ کے کنکشن سے اندازہ ہے اور محفوظ نہیں کیا جاتا۔",
    "change_place": "جگہ تبدیل کریں",
    "key_facts": "اہم معلومات",
    "specialities": "خصوصیات",
    "more_n": "+{n} مزید",
    "area": "علاقہ",
    "category": "زمرہ",
    "languages": "زبانیں",
    "year_established": "قیام",
    "services": "خدمات",
    "certificates": "سرٹیفکیٹس",
    "checks_title": "اس کی جانچ کیسے ہوئی",
    "address": "پتہ",
    "website": "ویب سائٹ",
    "not_found": "صفحہ نہیں ملا",
    "ad_label": "اشتہار",
    "subscriber_panel_body": "گلی کا پتہ، نقشے پر درست مقام، سائز، ویب سائٹ، سوشل صفحات، برآمدی منڈیاں، کم از کم آرڈر، تاریخ کے ساتھ قیمتیں اور سرٹیفکیٹ کی تفصیل۔",
    "something_wrong_body": "مسئلہ بتائیں، اس اندراج پر دعویٰ کریں، درستی تجویز کریں، یا اپنا ڈیٹا ہٹانے یا درست کرنے کو کہیں۔ یہ مفت ہے۔",
    "check_by": "از {who}",
    "check_expired": "میعاد ختم",
    "yes": "ہاں",
    "no": "نہیں",
    "closed_notice": "یہ کاروبار بند ہے۔ اس کی جانچ ماضی کے ریکارڈ کے طور پر دکھائی گئی ہے۔",
    "addon_business_type": "کاروبار کی قسم",
    "addon_product_categories": "مصنوعات",
    "addon_year_established": "قیام",
    "addon_years_exporting": "برآمد کے سال",
    "addon_export_markets": "برآمدی منڈیاں",
    "addon_certifications": "سرٹیفکیشن",
    "addon_oem": "او ای ایم کام",
    "addon_moq": "کم از کم آرڈر",
    "enum_manufacturer": "صنعت کار",
    "enum_trader": "تاجر",
    "enum_wholesaler": "تھوک فروش",
    "enum_exporter": "برآمد کنندہ",
    "map_pin": "نقشے پر مقام",
    "size": "سائز",
    "markets": "برآمدی منڈیاں",
    "min_order": "کم از کم آرڈر",
    "social": "سوشل صفحات",
    "title_entry": "{name} – {place} میں {list_type} – آل لسٹس",
    "title_list": "{place} میں {list_type} – آل لسٹس",
    "title_place": "{place} – فہرستیں – آل لسٹس",
    "title_home": "آل لسٹس – ہر چیز کی فہرست، جانچی ہوئی اور تاریخ کے ساتھ",
    "quota_notice": "آج کے مفت مشاہدات ختم ہو گئے۔ سبسکرائبرز کے لیے روزانہ کی حد نہیں۔ مفت مشاہدات کل دوبارہ شروع ہوں گے۔",
    "search_too_short": "کم از کم دو حروف لکھیں۔",
    "search_no_results": "کچھ نہیں ملا۔",
    "search_lists": "فہرستیں",
    "search_places": "مقامات",
    "search_entries": "اس علاقے کے کاروبار",
    "provided_by": "کمپنی کی فراہم کردہ معلومات۔",
    "company_updated": "تازہ کاری {date}",
    "cs_about": "کمپنی کے بارے میں",
    "cs_products": "مصنوعات اور خدمات",
    "cs_capacity": "صلاحیت اور سہولیات",
    "cs_terms": "شرائط اور نمونے",
    "cs_faq": "خریداروں کے سوالات",
    "company_certs": "کمپنی کے درج کردہ سرٹیفکیٹس",
    "checked_by_us": "آل لسٹس نے جانچا",
    "company_says": "کمپنی کا کہنا ہے",
    "company_prompt": "کیا یہ آپ کا کاروبار ہے؟ کمپنی کا صفحہ شامل کریں۔",
}
