"""Build docs/MASTER_DOCUMENT.md: every decision, detail, research note and the
design code in one file.  Run from the repo root:  python scripts/build_master_document.py
Optional: --transcript <jsonl> appends the founder's messages verbatim."""

import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / "docs" / "MASTER_DOCUMENT.md"
SKIP = (
    "<system-reminder",
    "[SYSTEM NOTIFICATION",
    "Stop hook feedback",
    "<task-notification",
    "Another Claude session",
    "<agent-message",
    "Caveat:",
    "<command-",
    "<local-command",
    "This session is being continued",
)


def fence(text, lang=""):
    ticks = "```"
    while ticks in text:
        ticks += "`"
    return f"{ticks}{lang}\n{text.rstrip()}\n{ticks}\n"


def demote(text, by=2):
    """Push headings down so the master TOC stays the top structure (skip code fences)."""
    out, infence = [], False
    for line in text.splitlines():
        if line.lstrip().startswith("```"):
            infence = not infence
        if not infence and re.match(r"#{1,6} ", line):
            line = "#" * min(6, by) + line
        out.append(line)
    return "\n".join(out)


REDACT = [
    (re.compile(r"glpat-[\w-]+"), "[REDACTED-TOKEN]"),
    (re.compile(r"(://[^\s:/@]+:)[^\s@]+(@)"), r"\1[REDACTED]\2"),
    (re.compile(r"\b(gh[pousr]_|sk-|AKIA|AIza)[\w-]{16,}"), "[REDACTED-TOKEN]"),
]


def redact(text):
    for rx, rep in REDACT:
        text = rx.sub(rep, text)
    return text


def founder_messages(path):
    msgs = []
    for line in Path(path).read_text(encoding="utf-8").splitlines():
        try:
            d = json.loads(line)
        except ValueError:
            continue
        if d.get("type") != "user" or d.get("isSidechain") or d.get("isMeta"):
            continue
        c = d.get("message", {}).get("content")
        if isinstance(c, list):
            c = "\n".join(b.get("text", "") for b in c if isinstance(b, dict) and b.get("type") == "text")
        if not isinstance(c, str) or not c.strip() or c.lstrip().startswith(SKIP):
            continue
        msgs.append(redact(c.strip()))
    return msgs


def main():
    parts = []  # (title, body)
    parts.append(("Project README", (ROOT / "README.md").read_text(encoding="utf-8")))
    for n in [
        "DECISIONS",
        "REQUIREMENTS",
        "TECHNICAL_CAPABILITIES",
        "REUSE_AND_TOOLS",
        "LIST_AND_ENTRY_COMPONENTS",
        "DESIGN_SYSTEM",
        "MODERN_UI_TOOLS",
        "NAME_AND_NAVIGATION",
        "TECHNICAL_PLAN",
        "DEPLOYMENT",
    ]:
        parts.append((f"docs/{n}.md", (ROOT / "docs" / f"{n}.md").read_text(encoding="utf-8")))
    for p in sorted((ROOT / "reports").glob("*.md")):
        parts.append((f"reports/{p.name}", p.read_text(encoding="utf-8")))
    for p in sorted((ROOT / "research_notes").rglob("*.md")):
        parts.append((f"research_notes/{p.relative_to(ROOT / 'research_notes')}", p.read_text(encoding="utf-8")))
    parts.append(("prototype/README.md", (ROOT / "prototype" / "README.md").read_text(encoding="utf-8")))

    code = []
    proto = ROOT / "prototype" / "alllists-prototype.html"
    code.append(
        ("Design code: full interactive prototype (single HTML file)", fence(proto.read_text(encoding="utf-8"), "html"))
    )
    for rel in (
        sorted(
            p.relative_to(ROOT).as_posix()
            for p in (ROOT / "backend").rglob("*")
            if p.is_file()
            and p.suffix in {".py", ".html", ".css", ".js", ".txt", ".ini", ".md"}
            and "__pycache__" not in p.parts
            and "migrations" not in p.parts
        )
        if (ROOT / "backend").exists()
        else []
    ):
        code.append((f"Software source: {rel}", fence((ROOT / rel).read_text(encoding="utf-8"), Path(rel).suffix[1:])))

    founder = []
    if "--transcript" in sys.argv:
        for i, m in enumerate(founder_messages(sys.argv[sys.argv.index("--transcript") + 1]), 1):
            founder.append(f"### Message {i}\n\n" + "\n".join("> " + line for line in m.splitlines()) + "\n")

    out = [
        "# AllLists.org: Master Document\n",
        "One file holding every decision, detail, research note, the design code and the software source, "
        "so work can restart from here. Generated by `scripts/build_master_document.py`; "
        "edit the source files, then regenerate.\n",
        "## Contents\n",
    ]
    n = 1
    for t, _ in parts:
        out.append(f"{n}. {t}")
        n += 1
    for t, _ in code:
        out.append(f"{n}. {t}")
        n += 1
    if founder:
        out.append(f"{n}. Appendix: founder's messages, verbatim")
    out.append("")
    n = 1
    for t, b in parts:
        out.append(f"\n---\n\n## {n}. {t}\n\n{demote(b)}\n")
        n += 1
    for t, b in code:
        out.append(f"\n---\n\n## {n}. {t}\n\n{b}\n")
        n += 1
    if founder:
        out.append(f"\n---\n\n## {n}. Appendix: founder's messages, verbatim\n\n" + "\n".join(founder))
    OUT.write_text("\n".join(out), encoding="utf-8")
    print(OUT, OUT.stat().st_size, "bytes")


main()
