# Generated by Django 5.2.17 on 2026-10-05 16:29

import core.clock
import core.crypto
import core.ulid
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("intake", "0001_initial"),
        ("places", "0001_initial"),
        ("taxonomy", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Entry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uid",
                    models.CharField(
                        default=core.ulid.new_ulid,
                        editable=False,
                        max_length=26,
                        unique=True,
                    ),
                ),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("tombstone_reason", models.CharField(blank=True, max_length=80)),
                ("country_code", models.CharField(db_index=True, max_length=2)),
                (
                    "entity_type",
                    models.CharField(
                        choices=[
                            ("business", "Business"),
                            ("facility", "Facility"),
                            ("person", "Person"),
                            ("institution", "Institution"),
                        ],
                        default="business",
                        max_length=12,
                    ),
                ),
                ("name", models.CharField(max_length=250)),
                ("name_lang", models.CharField(default="en", max_length=10)),
                ("name_fold", models.CharField(db_index=True, max_length=250)),
                ("description", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("temporarily_closed", "Temp Closed"),
                            ("permanently_closed", "Perm Closed"),
                            ("moved", "Moved"),
                        ],
                        default="open",
                        max_length=20,
                    ),
                ),
                ("status_date", models.DateField(blank=True, null=True)),
                (
                    "publish_state",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("review", "Review"),
                            ("published", "Published"),
                            ("suppressed", "Suppressed"),
                            ("tombstoned", "Tombstoned"),
                        ],
                        default="draft",
                        max_length=12,
                    ),
                ),
                ("address", models.JSONField(blank=True, default=dict)),
                ("address_text", models.CharField(blank=True, max_length=400)),
                ("place_path", models.CharField(max_length=500)),
                (
                    "lat",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "lon",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                ("precision_class", models.CharField(blank=True, max_length=10)),
                ("coord_source", models.CharField(blank=True, max_length=40)),
                ("coord_date", models.DateField(blank=True, null=True)),
                ("service_area", models.JSONField(blank=True, default=dict)),
                ("website", models.URLField(blank=True)),
                ("size_band", models.CharField(blank=True, max_length=20)),
                (
                    "year_established",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                ("languages", models.JSONField(blank=True, default=list)),
                ("price_band", models.CharField(blank=True, max_length=10)),
                ("payment_methods", models.JSONField(blank=True, default=list)),
                ("addons", models.JSONField(blank=True, default=dict)),
                (
                    "addon_template_version",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "claim_state",
                    models.CharField(
                        choices=[
                            ("unclaimed", "Unclaimed"),
                            ("pending", "Pending"),
                            ("claimed", "Claimed"),
                        ],
                        default="unclaimed",
                        max_length=10,
                    ),
                ),
                ("listing_plan", models.CharField(default="basic", max_length=10)),
                ("plan_valid_until", models.DateField(blank=True, null=True)),
                ("visibility_flags", models.JSONField(blank=True, default=list)),
                (
                    "created_via",
                    models.CharField(
                        choices=[
                            ("contributor", "Contributor"),
                            ("import", "Import"),
                            ("agent", "Agent"),
                            ("register", "Register"),
                            ("self", "Self"),
                        ],
                        default="contributor",
                        max_length=12,
                    ),
                ),
                ("phase_id", models.PositiveIntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(default=core.clock.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("last_verified_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "merged_into",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="merged_from",
                        to="entries.entry",
                    ),
                ),
                (
                    "parent_entry",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="branches_of",
                        to="entries.entry",
                    ),
                ),
                (
                    "place",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="entries",
                        to="places.place",
                    ),
                ),
                (
                    "primary_concept",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="taxonomy.concept",
                    ),
                ),
                (
                    "secondary_concepts",
                    models.ManyToManyField(
                        blank=True,
                        related_name="secondary_entries",
                        to="taxonomy.concept",
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="intake.source",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "entries",
            },
        ),
        migrations.CreateModel(
            name="CreditEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("kind", models.CharField(max_length=20)),
                ("eligible", models.BooleanField(default=False)),
                ("ineligible_reason", models.CharField(blank=True, max_length=60)),
                ("phase_id", models.PositiveIntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(default=core.clock.now)),
                ("merged_from_id", models.BigIntegerField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "entry",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="credit_events",
                        to="entries.entry",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("country_code", models.CharField(max_length=2)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("phone", "Phone"),
                            ("mobile", "Mobile"),
                            ("whatsapp", "Whatsapp"),
                            ("email", "Email"),
                            ("fax", "Fax"),
                        ],
                        max_length=10,
                    ),
                ),
                ("value_enc", core.crypto.EncryptedTextField()),
                ("value_hash", models.CharField(db_index=True, max_length=64)),
                ("label", models.CharField(blank=True, max_length=20)),
                ("preferred_hours", models.CharField(blank=True, max_length=60)),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                ("relay_only", models.BooleanField(default=True, editable=False)),
                ("optin_state", models.CharField(default="none", max_length=12)),
                (
                    "entry",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_set",
                        to="entries.entry",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ConsentRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("subject_kind", models.CharField(default="entry", max_length=10)),
                ("status", models.CharField(max_length=12)),
                ("method", models.CharField(max_length=40)),
                ("wording_version", models.CharField(max_length=20)),
                ("evidence_text", models.TextField(blank=True)),
                ("at", models.DateTimeField(default=core.clock.now)),
                (
                    "entry",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="consents",
                        to="entries.entry",
                    ),
                ),
            ],
            options={
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="Claim",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("method", models.CharField(max_length=20)),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=10,
                    ),
                ),
                ("evidence_text", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(default=core.clock.now)),
                ("decided_by_id", models.BigIntegerField(blank=True, null=True)),
                ("decided_at", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "entry",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="claims",
                        to="entries.entry",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Branch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("country_code", models.CharField(max_length=2)),
                ("address_text", models.CharField(blank=True, max_length=400)),
                (
                    "lat",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "lon",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "entry",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_set",
                        to="entries.entry",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="AreaServed",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("country_code", models.CharField(max_length=2)),
                ("radius_km", models.PositiveIntegerField(blank=True, null=True)),
                ("notes", models.CharField(blank=True, max_length=200)),
                (
                    "place",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="places.place",
                    ),
                ),
                (
                    "entry",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_set",
                        to="entries.entry",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Equipment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("country_code", models.CharField(max_length=2)),
                ("type", models.CharField(max_length=80)),
                ("make_model", models.CharField(blank=True, max_length=120)),
                ("quantity", models.PositiveIntegerField(default=1)),
                ("modality", models.CharField(blank=True, max_length=60)),
                (
                    "installed_year",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                ("services_supported", models.JSONField(blank=True, default=list)),
                (
                    "entry",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_set",
                        to="entries.entry",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Hours",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("country_code", models.CharField(max_length=2)),
                ("day_from", models.PositiveSmallIntegerField()),
                ("day_to", models.PositiveSmallIntegerField()),
                ("open_time", models.TimeField(blank=True, null=True)),
                ("close_time", models.TimeField(blank=True, null=True)),
                ("appointment_only", models.BooleanField(default=False)),
                ("confirmed_on", models.DateField(blank=True, null=True)),
                ("tz", models.CharField(blank=True, max_length=40)),
                (
                    "entry",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_set",
                        to="entries.entry",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Identifier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("country_code", models.CharField(max_length=2)),
                ("scheme", models.CharField(max_length=30)),
                ("value", models.CharField(max_length=80)),
                ("issuer", models.CharField(blank=True, max_length=120)),
                ("valid_from", models.DateField(blank=True, null=True)),
                ("valid_to", models.DateField(blank=True, null=True)),
                ("last_checked", models.DateField(blank=True, null=True)),
                ("register_url", models.URLField(blank=True)),
                (
                    "entry",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_set",
                        to="entries.entry",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="NameVariant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("country_code", models.CharField(max_length=2)),
                ("text", models.CharField(max_length=250)),
                ("language", models.CharField(blank=True, max_length=10)),
                ("kind", models.CharField(default="trade", max_length=15)),
                ("text_fold", models.CharField(db_index=True, max_length=250)),
                (
                    "entry",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_set",
                        to="entries.entry",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("country_code", models.CharField(max_length=2)),
                ("name_text", models.CharField(max_length=200)),
                ("brand", models.CharField(blank=True, max_length=100)),
                ("unit", models.CharField(blank=True, max_length=40)),
                ("price_band", models.CharField(blank=True, max_length=10)),
                ("availability_note", models.CharField(blank=True, max_length=200)),
                ("price_date", models.DateField(blank=True, null=True)),
                (
                    "concept",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="taxonomy.concept",
                    ),
                ),
                (
                    "entry",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_set",
                        to="entries.entry",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Service",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("country_code", models.CharField(max_length=2)),
                ("name_text", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                ("price_minor", models.BigIntegerField(blank=True, null=True)),
                ("currency", models.CharField(blank=True, max_length=3)),
                ("price_type", models.CharField(blank=True, max_length=10)),
                ("unit", models.CharField(blank=True, max_length=40)),
                ("price_date", models.DateField(blank=True, null=True)),
                ("prep_notes", models.CharField(blank=True, max_length=300)),
                (
                    "concept",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="taxonomy.concept",
                    ),
                ),
                (
                    "entry",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_set",
                        to="entries.entry",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Social",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("country_code", models.CharField(max_length=2)),
                ("platform", models.CharField(max_length=30)),
                ("handle_or_url", models.CharField(max_length=300)),
                ("owner_confirmed", models.BooleanField(default=False)),
                ("last_link_check", models.DateTimeField(blank=True, null=True)),
                ("link_status", models.CharField(blank=True, max_length=10)),
                (
                    "entry",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_set",
                        to="entries.entry",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Speciality",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("country_code", models.CharField(max_length=2)),
                ("qualification", models.CharField(blank=True, max_length=200)),
                ("own_hours", models.CharField(blank=True, max_length=120)),
                (
                    "concept",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="taxonomy.concept",
                    ),
                ),
                (
                    "entry",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_set",
                        to="entries.entry",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ValueMeta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("country_code", models.CharField(max_length=2)),
                ("field_key", models.CharField(max_length=60)),
                ("licence_text", models.CharField(blank=True, max_length=200)),
                ("retrieved_at", models.DateTimeField(default=core.clock.now)),
                ("level", models.CharField(default="none", max_length=10)),
                ("verified_by_id", models.BigIntegerField(blank=True, null=True)),
                ("method", models.CharField(blank=True, max_length=40)),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("evidence_text", models.TextField(blank=True)),
                ("consent_ref", models.CharField(blank=True, max_length=40)),
                ("confidence", models.FloatField(blank=True, null=True)),
                (
                    "entry",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="value_meta",
                        to="entries.entry",
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="intake.source",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="VerificationCurrent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("field_group", models.CharField(max_length=20)),
                ("level", models.CharField(max_length=10)),
                ("state", models.CharField(max_length=10)),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("method", models.CharField(blank=True, max_length=40)),
                ("actor_display", models.CharField(blank=True, max_length=80)),
                (
                    "entry",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="verification_current",
                        to="entries.entry",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="VerificationEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("country_code", models.CharField(max_length=2)),
                ("field_group", models.CharField(max_length=20)),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("surveyor", "Surveyor"),
                            ("owner", "Owner"),
                            ("ai", "Ai"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("verified", "Verified"),
                            ("expired", "Expired"),
                            ("revoked", "Revoked"),
                        ],
                        max_length=10,
                    ),
                ),
                ("actor_id", models.BigIntegerField(blank=True, null=True)),
                ("method", models.CharField(blank=True, max_length=40)),
                ("evidence_text", models.TextField(blank=True)),
                ("ts", models.DateTimeField(default=core.clock.now)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                (
                    "entry",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="verification_events",
                        to="entries.entry",
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="intake.source",
                    ),
                ),
                (
                    "supersedes",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="entries.verificationevent",
                    ),
                ),
            ],
            options={
                "ordering": ["id"],
            },
        ),
        migrations.AddIndex(
            model_name="entry",
            index=models.Index(
                fields=[
                    "country_code",
                    "place_path",
                    "primary_concept",
                    "publish_state",
                ],
                name="entry_list_query",
            ),
        ),
        migrations.AddIndex(
            model_name="entry",
            index=models.Index(
                fields=["country_code", "claim_state"], name="entry_claim_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="valuemeta",
            unique_together={("entry", "field_key")},
        ),
        migrations.AlterUniqueTogether(
            name="verificationcurrent",
            unique_together={("entry", "field_group", "level")},
        ),
    ]
