# Generated by Django 5.2.17 on 2026-10-05 16:35

import core.clock
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("entries", "0002_append_only_and_indexes"),
    ]

    operations = [
        migrations.CreateModel(
            name="MergeMap",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("score", models.FloatField(blank=True, null=True)),
                ("decided_by_id", models.BigIntegerField(blank=True, null=True)),
                ("decided_at", models.DateTimeField(default=core.clock.now)),
                (
                    "from_entry",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="entries.entry",
                    ),
                ),
                (
                    "to_entry",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="entries.entry",
                    ),
                ),
            ],
        ),
    ]
