# Generated by Django 5.2.17 on 2026-10-05 18:59

import core.clock
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("entries", "0003_mergemap"),
    ]

    operations = [
        migrations.CreateModel(
            name="CompanySection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("about", "About"),
                            ("products", "Products"),
                            ("capacity", "Capacity"),
                            ("terms", "Terms"),
                            ("faq", "Faq"),
                        ],
                        max_length=10,
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=160)),
                ("body", models.TextField(max_length=4000)),
                ("sort", models.PositiveSmallIntegerField(default=0)),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=10,
                    ),
                ),
                ("updated_at", models.DateTimeField(default=core.clock.now)),
                ("moderated_by_id", models.BigIntegerField(blank=True, null=True)),
                (
                    "entry",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="company_sections",
                        to="entries.entry",
                    ),
                ),
            ],
        ),
    ]
