# Generated by Django 5.2.17 on 2026-10-05 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("entries", "0005_stewardgrant"),
    ]

    operations = [
        migrations.AddField(
            model_name="verificationcurrent",
            name="actor_id",
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
