# Generated by Django 5.2.17 on 2026-10-05 19:00

import core.clock
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("taxonomy", "0002_indexes"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RatePhase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=40)),
                ("starts_on", models.DateField()),
                ("ends_on", models.DateField(blank=True, null=True)),
                ("rate_percent", models.PositiveSmallIntegerField()),
                ("cap_months", models.PositiveSmallIntegerField(default=36)),
            ],
            options={
                "ordering": ["starts_on"],
            },
        ),
        migrations.CreateModel(
            name="LedgerAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("clearing", "Clearing"),
                            ("platform", "Platform"),
                            ("fees", "Fees"),
                            ("tax", "Tax"),
                            ("holding", "Holding"),
                            ("payable", "Payable"),
                            ("payout", "Payout"),
                            ("refund", "Refund"),
                            ("credit", "Credit"),
                        ],
                        max_length=10,
                    ),
                ),
                ("currency", models.CharField(default="USD", max_length=3)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LedgerTxn",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("idempotency_key", models.CharField(max_length=80, unique=True)),
                ("kind", models.CharField(max_length=12)),
                ("ref", models.CharField(blank=True, max_length=60)),
                ("memo", models.CharField(blank=True, max_length=200)),
                ("ts", models.DateTimeField(default=core.clock.now)),
                (
                    "reverses",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reversed_by",
                        to="ledger.ledgertxn",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LedgerPosting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount_minor", models.BigIntegerField()),
                ("currency", models.CharField(default="USD", max_length=3)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="postings",
                        to="ledger.ledgeraccount",
                    ),
                ),
                (
                    "txn",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="postings",
                        to="ledger.ledgertxn",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Payout",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("currency", models.CharField(default="USD", max_length=3)),
                ("amount_minor", models.BigIntegerField()),
                ("method", models.CharField(blank=True, max_length=30)),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("paid", "Paid"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=10,
                    ),
                ),
                ("external_ref", models.CharField(blank=True, max_length=80)),
                ("created_at", models.DateTimeField(default=core.clock.now)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "txn",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="ledger.ledgertxn",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payouts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Sale",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order_ref", models.CharField(max_length=40, unique=True)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("list", "List"),
                            ("subscription", "Subscription"),
                            ("listing", "Listing"),
                            ("rank", "Rank"),
                            ("extract", "Extract"),
                            ("outreach", "Outreach"),
                        ],
                        max_length=14,
                    ),
                ),
                ("scope_path", models.CharField(blank=True, max_length=500)),
                ("currency", models.CharField(default="USD", max_length=3)),
                ("gross_minor", models.BigIntegerField()),
                ("fees_minor", models.BigIntegerField(default=0)),
                ("tax_minor", models.BigIntegerField(default=0)),
                ("net_minor", models.BigIntegerField()),
                (
                    "state",
                    models.CharField(
                        choices=[("recorded", "Recorded"), ("refunded", "Refunded")],
                        default="recorded",
                        max_length=10,
                    ),
                ),
                ("ts", models.DateTimeField(default=core.clock.now)),
                (
                    "concept",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="taxonomy.concept",
                    ),
                ),
                (
                    "txn",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sale",
                        to="ledger.ledgertxn",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SaleAllocation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("entry_count", models.PositiveIntegerField()),
                ("amount_minor", models.BigIntegerField()),
                ("hold_until", models.DateTimeField()),
                ("released_at", models.DateTimeField(blank=True, null=True)),
                ("reversed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "sale",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="allocations",
                        to="ledger.sale",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="ledgeraccount",
            constraint=models.UniqueConstraint(fields=("kind", "user", "currency"), name="uniq_ledger_account"),
        ),
    ]
