# Generated by Django 5.2.17 on 2026-10-05 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ledger", "0002_balance_and_append_only"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sale",
            name="kind",
            field=models.CharField(
                choices=[
                    ("list", "List"),
                    ("subscription", "Subscription"),
                    ("listing", "Listing"),
                    ("rank", "Rank"),
                    ("extract", "Extract"),
                    ("outreach", "Outreach"),
                    ("ad", "Ad"),
                ],
                max_length=14,
            ),
        ),
    ]
