# Generated by Django 5.2.17 on 2026-10-05 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ledger", "0004_payoutbatch_payout_batch_payoutprofile"),
    ]

    operations = [
        migrations.AddField(
            model_name="payout",
            name="details_hash",
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
