# Generated by Django 5.2.17 on 2026-10-05 16:29

import core.clock
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ts", models.DateTimeField()),
                ("actor_id", models.BigIntegerField(blank=True, null=True)),
                ("actor_role", models.CharField(blank=True, max_length=40)),
                ("action", models.CharField(max_length=80)),
                ("object_type", models.CharField(blank=True, max_length=60)),
                ("object_uid", models.CharField(blank=True, max_length=40)),
                ("country_code", models.CharField(blank=True, max_length=2)),
                ("ip_hash", models.CharField(blank=True, max_length=64)),
                ("payload", models.JSONField(blank=True, default=dict)),
                ("prev_hash", models.CharField(blank=True, max_length=64)),
                ("hash", models.CharField(max_length=64, unique=True)),
            ],
            options={
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="ChangeLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("entry_id", models.BigIntegerField(db_index=True)),
                ("country_code", models.CharField(max_length=2)),
                ("field_key", models.CharField(max_length=60)),
                ("old", models.JSONField(blank=True, null=True)),
                ("new", models.JSONField(blank=True, null=True)),
                ("actor_id", models.BigIntegerField(blank=True, null=True)),
                ("source_id", models.BigIntegerField(blank=True, null=True)),
                ("ts", models.DateTimeField(default=core.clock.now)),
            ],
            options={
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="CountrySwitch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("country_code", models.CharField(max_length=2, unique=True)),
                ("browsing_on", models.BooleanField(default=True)),
                ("indexing_on", models.BooleanField(default=False)),
                ("selling_on", models.BooleanField(default=False)),
                ("outreach_on", models.BooleanField(default=False)),
                ("outreach_channels", models.JSONField(blank=True, default=list)),
                ("ads_on", models.BooleanField(default=False)),
                ("named_individuals_on", models.BooleanField(default=False)),
                ("health_prices_on", models.BooleanField(default=False)),
                ("child_services_on", models.BooleanField(default=False)),
                ("publish_cap_per_week", models.PositiveIntegerField(default=0)),
                ("legal_note", models.TextField(blank=True)),
                ("cleared_by", models.CharField(blank=True, max_length=120)),
                ("cleared_on", models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="FeatureFlag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.CharField(max_length=60, unique=True)),
                ("description", models.CharField(blank=True, max_length=200)),
                ("enabled_default", models.BooleanField(default=False)),
                (
                    "country_code",
                    models.CharField(blank=True, help_text="Blank means every country", max_length=2),
                ),
                ("rollout_percent", models.PositiveSmallIntegerField(default=100)),
            ],
        ),
        migrations.CreateModel(
            name="RegistryVersion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("registry_key", models.CharField(max_length=60)),
                ("version", models.PositiveIntegerField()),
                ("changed_at", models.DateTimeField(default=core.clock.now)),
                ("changed_by", models.CharField(blank=True, max_length=120)),
            ],
            options={
                "unique_together": {("registry_key", "version")},
            },
        ),
    ]
