# Generated by Django 5.2.17 on 2026-10-05 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_append_only"),
    ]

    operations = [
        migrations.CreateModel(
            name="JobRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=60, unique=True)),
                ("last_run", models.DateTimeField(blank=True, null=True)),
                ("last_result", models.CharField(blank=True, max_length=200)),
                ("last_error", models.CharField(blank=True, max_length=300)),
            ],
        ),
    ]
