# Generated by Django 5.2.17 on 2026-10-05 19:45

import core.clock
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_jobrun"),
    ]

    operations = [
        migrations.CreateModel(
            name="OpsRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("kind", models.CharField(db_index=True, max_length=30)),
                ("key", models.CharField(blank=True, max_length=120)),
                ("detail", models.CharField(blank=True, max_length=300)),
                ("at", models.DateTimeField(default=core.clock.now)),
            ],
        ),
    ]
