"""All interface text, English and Urdu, in one place. Missing Urdu keys fall back to English."""
EN = {
    "site": "AllLists", "tagline": "Lists of anything, checked and dated.",
    "search": "Search this list", "search_go": "Search", "skip": "Skip to content",
    "near_you": "Near you", "choose_place": "Choose a place", "guess_note": "Guessed from your connection. Change it any time.",
    "chosen_note": "You chose this place.", "no_place": "We could not tell where you are. Choose a place.",
    "countries": "Countries", "places_in": "Places in", "lists_here": "Lists here", "entries": "entries",
    "widen": "Widen search", "widen_note": "Names only on a wider list. Subscribe for full details.",
    "all_areas": "All areas", "sort": "Sort", "sort_name": "Name", "sort_checked": "Last checked",
    "view_list": "List", "view_cards": "Cards", "trust": "of entries checked by a person",
    "level_surveyor": "Surveyor-verified", "level_owner": "Owner-verified", "level_ai": "AI-checked",
    "level_none": "Not verified yet", "checked": "Checked", "closed": "Closed", "moved": "Moved",
    "company": "Company page", "sponsored": "Sponsored", "locked": "Subscribe to see this",
    "subscribe": "Subscribe", "address": "Address", "website": "Website", "size": "Size", "markets": "Markets",
    "moq": "Minimum order", "prices": "Prices", "certificates": "Certificates", "services": "Services",
    "specialities": "Specialities", "more": "more", "social": "Social pages", "map": "Map pin",
    "provided_by": "Provided by the company.", "contact_note": "Phone, WhatsApp and email are never shown. Send an enquiry and we pass it on.",
    "enquiry": "Send one enquiry to many", "your_email": "Your email", "message": "Message", "send": "Send",
    "enquiry_sent": "Enquiry sent. Suppliers reply to you directly.", "subscribers_only": "Enquiries are for subscribers.",
    "report": "Report a problem", "claim": "Claim this entry", "note": "Note", "contact": "How we can reach you",
    "submitted": "Thank you. We will check it.", "share": "Share", "share_more": "More",
    "empty_title": "Nothing here yet", "empty_body": "No entries in this list. Be the first to add one.",
    "ads": "Advertisement", "home": "Home", "theme": "Theme", "language": "Language", "demo_plan": "Preview plan",
    "plan_free": "Free", "plan_subscriber": "Subscriber", "ok": "OK",
    "legal": "AllLists is a register: verified where marked, and dated. Contacts are never shown.",
    "not_found": "Page not found",
}
UR = {
    "tagline": "ہر چیز کی فہرست، جانچی ہوئی اور تاریخ کے ساتھ۔", "search": "اس فہرست میں تلاش کریں",
    "search_go": "تلاش", "skip": "مواد پر جائیں", "near_you": "آپ کے قریب", "choose_place": "جگہ منتخب کریں",
    "countries": "ممالک", "places_in": "مقامات", "lists_here": "یہاں کی فہرستیں", "entries": "اندراجات",
    "widen": "تلاش وسیع کریں", "all_areas": "تمام علاقے", "sort": "ترتیب", "sort_name": "نام",
    "sort_checked": "آخری جانچ", "view_list": "فہرست", "view_cards": "کارڈز",
    "level_surveyor": "سروے کنندہ سے تصدیق شدہ", "level_owner": "مالک سے تصدیق شدہ",
    "level_ai": "اے آئی سے جانچا ہوا", "level_none": "ابھی تصدیق نہیں", "checked": "جانچ",
    "closed": "بند", "company": "کمپنی کا صفحہ", "sponsored": "اسپانسر شدہ", "locked": "دیکھنے کے لیے سبسکرائب کریں",
    "subscribe": "سبسکرائب", "address": "پتہ", "website": "ویب سائٹ", "services": "خدمات",
    "specialities": "خصوصیات", "enquiry": "ایک پیغام کئی سپلائرز کو", "send": "بھیجیں", "report": "مسئلہ بتائیں",
    "claim": "اندراج پر دعویٰ کریں", "share": "شیئر", "home": "ہوم", "language": "زبان", "theme": "تھیم",
    "empty_title": "ابھی کچھ نہیں",
}
STRINGS = {"en": EN, "ur": {**EN, **UR}}
